version: '3.8'

services:
  dashboard:
    build: .
    container_name: autosocial-dashboard
    restart: unless-stopped
    ports:
      - "5173:80" # host:container
    networks:
      - autosocial-network

networks:
  autosocial-network:
    driver: bridge
